name: hostal
recipe: wordpress
config:
  webroot: .
services:
  database:
    type: mysql #type de DB
    portforward: 3307 #Port sur lequel on va écouter
    creds:
      user: "zak" #Nom d'utilisateur de DB
      password: "z@kou" #Password de DB
      database: "lhobase" #Nom de la DB
tooling:
  install:
    service: appserver
    description: "commande pour installer worpress"
    cmd:
      - echo Installation Wordpress....
      - php config/install_wp.php